/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#380d00",
        "on-surface-variant": "#434654",
        "surface": "#fff8f1",
        "on-secondary-fixed": "#021945",
        "on-tertiary-fixed-variant": "#812800",
        "secondary": "#4c5d8d",
        "on-secondary-fixed-variant": "#344573",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#415382",
        "surface-variant": "#e9e1d8",
        "surface-tint": "#0c56d0",
        "tertiary-container": "#a33500",
        "surface-container-highest": "#e9e1d8",
        "on-primary-container": "#c4d2ff",
        "on-secondary": "#ffffff",
        "primary": "#003d9b",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b4c5fb",
        "on-tertiary-container": "#ffc6b2",
        "secondary-fixed": "#dae2ff",
        "inverse-surface": "#33302a",
        "surface-container": "#f5ede3",
        "on-primary-fixed-variant": "#0040a2",
        "primary-container": "#0052cc",
        "surface-dim": "#e0d9cf",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d6",
        "surface-container-low": "#faf2e9",
        "surface-container-high": "#efe7dd",
        "outline": "#737685",
        "inverse-primary": "#b2c5ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "on-background": "#1e1b15",
        "on-surface": "#1e1b15",
        "background": "#fff8f1",
        "tertiary": "#7b2600",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f1",
        "primary-fixed-dim": "#b2c5ff",
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Public Sans", "sans-serif"],
        "body": ["Chivo", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}